# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "testomial-test"
client_id = "f54e91bf2e5198477d54e7d8fee714ea"
application_url = "https://volt-volunteers-workplace-barbara.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_discounts,write_discounts,write_pixels,read_customer_events"

[auth]
redirect_urls = [
  "https://volt-volunteers-workplace-barbara.trycloudflare.com/auth/callback",
  "https://volt-volunteers-workplace-barbara.trycloudflare.com/auth/shopify/callback",
  "https://volt-volunteers-workplace-barbara.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "checout-modification.myshopify.com"
